### DISCUSSION TITLE
endpoint with google sheet content (and other cloud file services)

### DISCUSSION THREAD

**Discussion by avelino** [moclojer/moclojer#116] [Ideas]
I was thinking about the future of the project and whether we should bring other types of integrations into the moclojer core.

e.g. Google Sheet integration

putting moclojer as a no-code tool to transform spreadsheet (google sheet) in api

configuration:

```yaml
- endpoint:
    method: GET
    path: /google-sheet-file1
    response:
      status: 200
      headers:
        Content-Type: application/json
      external-body:
        provider: gsheet
        file: https://docs.google.com/spreadsheets/d/...
```

---

If you have declared the configuration `body` and `external-body` on the same endpoint, the `body` will have **higher priority**, *allowing external requests to the cloud service*.

**tabs:** ends tab becomes a “sub endpoint” of the api, example where the file has the following tabs tab1, tab2 and tab3, the endpoint for this file would look like this:

* `/google-sheet-file1` - _“first tab” is not named (tab1), if it is possible to identify which is the first tab_
* `/google-sheet-file1/tab2`
* `/google-sheet-file1/tab3`

> I haven't thought much about how to access private files (how to pass access tokens), it is a subject that we need to evolve this discussion to turn it into an issue when we have the minimum defined.
