### DISCUSSION TITLE
Generative response body

### DISCUSSION THREAD

**Discussion by matheusfrancisco** [moclojer/moclojer#157] [Ideas]
I was thinking we could add something to use generative schema.
I define the body schema from the yaml and I generate random body for it.

```yaml
- endpoint:
    # Note: the method could be omitted because GET is the default
    method: GET
    path: /hello/:username
    response:
      status: 200
      scheme: {body: {string: string}}
```
every call we will generate a random output body {"hello": "name"}

**Comment by avelino** [comment]
I like the idea of implementing a scheme that makes the api return "dynamic"

we can use a ready-made library to dynamically generate the returns, e.g. [faker](https://github.com/paraseba/faker)

```yaml
- endpoint:
    # Note: the method could be omitted because GET is the default
    method: GET
    path: /hello/:username
    response:
      status: 200
      body: {"name": "{{faker/names}}"}
```

**`faker/names`:**
```clj
(ns test
  (:require [faker.name :as name])
  (:use faker.name faker.lorem))

(println name.names)
```
