### DISCUSSION TITLE
postback support (webhook)

### DISCUSSION THREAD

**Discussion by avelino** [moclojer/moclojer#173] [Ideas]
asynchronous endpoint (which does not respond to the payload as soon as it receives the request), returns the identification (id), after X time makes a request to an "external api" (or another mock endpoint).

background processing can be a sleep (waiting time)

```yaml
- endpoint:
    method: POST
    path: /with-postback
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: {"id": 123}
    postback:
      sleep: 60 # in seconds
      webhook:
        field: webhook # field with url
        method: POST
        ... # other parameters for calling the api, ex auth
      body: {"id": 123, "another-field": "it's working"}
```

**example:**

```sh
curl
  --header "Content-Type: application/json" \
  --request POST \
  --data '{"webhook": "https://127.0.0.1:3000/my-endpoint-that-will-receive-the-postback"}' \
  /with-postback
```

**Comment by matheusfrancisco** [comment]
Wdyt in remove ~~postback~~ from the spec since it is under the postback path

```yaml
- endpoint:
    method: POST
    path: /with-postback
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: {"id": 123}
    webhook:
      path: https://api.test.com/api/webhook/:id/something #it will call an webhook with the id 123
      method: POST
      sleep: 60 # in seconds
        ... # other parameters for calling the api, ex auth
      body: {"id": 123, "another-field": "it's working"}

```
