### DISCUSSION TITLE
`"shell"` script execution

### DISCUSSION THREAD

**Discussion by avelino** [moclojer/moclojer#268] [Ideas]
Today we do not grant access to the file system for executing binaries or scripts, would this be an interesting feature for the open source version of moclojer?

Reference https://github.com/adnanh/webhook

```yaml
- endpoint:
    method: POST
    path: /with-webhook-exec
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {"id": 123}
    script:
      sleep-time: 60
      if: 1 = 1
      exec: /bin/bash
      path: /home/moclojer/scripts/check-memory.sh
```

> **there may be a security risk**; if implementation makes sense, we need to discuss it thoroughly before proceeding
