### DISCUSSION TITLE
Configurable base folder for external bodies

### DISCUSSION THREAD

**Discussion by michaldo** [moclojer/moclojer#326] [Ideas]
Hi,
I'm using moclojer with docker compose. I have folder with N bodies, let say `/host/bodies`
My docker-compose.yaml has section

```
volumes:
  - /host/bodies:/app/bodies
```

My moclojer.yml has:
```
- endpoint:
    method: POST
    path: /body1
    response:
      external-body:
        provider: json
        path: bodies/body1.json
```

I'm not satisfied I had to repeat "path: **bodies**/body1.json" N times

I would be happy to repeat `path: body1.json`

If there is a configuration option like `external-bodies-base-folder=./bodies` my moclojer.yml will be simpler
