### ISSUE TITLE
endpoint with `xlsx` content

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#152]
support excel document (`xlsx`) content on endpoint return
> discussed in #116

**table:**

name | langs
-- | --
avelino | clojure, go
chicao | clojure, python

**response *(expected)*:**
```json
[{"name": "avelino", "langs": "clojure, go"},
{"name": "chicao","langs": "clojure, python"}]
```

```yaml
- endpoint:
    method: GET
    path: /xlsx
    response:
      status: 200
      headers:
        Content-Type: application/json
      external-body:
        provider: xlsx
        path: test/moclojer/resources/lerolero.xlsx
        sheet-name: test
```
