### ISSUE TITLE
include file in body endpoint return

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#160]
### Discussed in https://github.com/moclojer/moclojer/discussions/159

<div type='discussions-op-text'>

<sup>Originally posted by **avelino** October 20, 2023</sup>
Specifying large returns in the same **moclojer** configuration file (`.yaml` or any format) is _"boring"_ and makes the specification file difficult to read.

**Why not support the file inclusion tag for the body?**

```yaml
- endpoint:
    method: GET
    path: /external-body-text
    response:
      status: 200
      headers:
        Content-Type: application/json
      external-body:
        provider: text
        path: test/moclojer/resources/text-plan.json
```

> using the specification `external-body` created for xlsx support #152</div>
