### ISSUE TITLE
`extend-body.path`: dynamic path support based on request

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#166]
**How do I load a dynamic file based on the endpoint parameter _(URI)_?

Today there is no support for making the file path dynamic.

## use case

Is there an intense list of Pokémon (or anything):

* kabuto
* marowak
* cubone
* armaldo

```yaml
- endpoint:
    method: GET
    path: /pokemon/:name
    response:
      status: 200
      headers:
        Content-Type: application/json
      external-body:
        provider: json
        path: https://pokeapi.co/api/v2/pokemon/{{path-params.name}}
```

URI's:

* GET `/pokemon/kabuto`
* GET `/pokemon/marowak`
* GET `/pokemon/cubone`
* GET `/pokemon/armaldo`
