### ISSUE TITLE
endpoint to file upload

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#20]
```yaml
- endpoint:
    method: POST
    path: /file-upload
    store: upload-filesystem
    interceptor: multipart
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {
          "url": "https:/..."
        }
```

There are two variables that we need to control in this type of endpoint: **store** (where the file will be persisted) and **interceptor** (will it receive the file or in base64 format).

**example:**
```yaml
store: upload-filesystem
interceptor: multipart
```

**store:**
- `upload-filesystem`
- `upload-s3`

**interceptor's:**
- `file-multipart`
- `file-base64`

**ToDo:**
- [ ] moclojer spec
- [x] OpenAPI

**Comment by matheusfrancisco** [comment]
Let me see if I understood correctly.
This post endpoint if the store: is `upload-filesystem` we need to implement an interceptor that will get the file from post and save it in the file system, and the same thing to s3 if has store: `upload-s3`we need to save the content of the post into a bucket. Do I understand it correctly?

is the URL returned from the body the locally which this file was saved? 
```yaml
 body: >
        {
          "url": "https:/..."
        }
```
