### ISSUE TITLE
automatically generate documentation - openAPI (swagger)

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#205]
### Discussed in https://github.com/moclojer/moclojer/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **avelino** November  6, 2023</sup>
Have an option in the endpoint configuration to generate endpoint **documentation** (with swagger)

```yaml
- endpoint:
    method: GET
    path: /hello/:username
    doc: true # or `swagger: true`
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {
          "hello": "{{path-params.username}}!"
        }
```

> The OpenAPI Specification is a specification language for HTTP APIs that provides a standardized means to define your API to others. You can quickly discover how an API works, configure infrastructure, generate client code, and create test cases for your APIs. Read more about how you can get control of your APIs now, understand the full API lifecycle and communicate with developer communities inside and outside your organization.</div>
