### ISSUE TITLE
Watcher is not restarting the moclojer when I change the spec file

### ISSUE THREAD

**Issue by matheusfrancisco** [moclojer/moclojer#208]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Watcher is not starting the moclojer.
I'm passing the file `/Users/matheus.machado/.config/moclojer.yaml`  but when I change and i see the path it is
this one `[sun.nio.fs.UnixPath 0x6147ea1e "/Users/matheus.machado/dev/m/cljam/moclojer/moclojer.yaml"] `
but the correctly path it should be this one `/Users/matheus.machado/.config/moclojer.yaml`

### Reproduce the Bug

Run moclojer and change the endpoint, you should expect it changes but it doesn’t .

### moclojer config

```yaml
# This mock register route: GET /hello/:username
- endpoint:
    method: GET
    path: /hello/:username
    response:
      # Note: the status could be omitted because 200 is the default
      status: 200
      headers:
        Content-Type: application/json
      # Note: the body will receive the value passed in the url using the
      # :username placeholder
      body: >
        {
          "hello": "{{path-params.username}}!"
        }

```

### Expected Behavior

Change the mocks and it should restart the server with the new files.

### Version and environment information

OSX

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)
