### ISSUE TITLE
docker no main manifest attribute, in /app/moclojer.jar

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#210]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

up moclojer server

> bug was generated in this issue #190

### Reproduce the Bug

1. run `docker run -it -p 8000:8000 -v ./src/test/moclojer.yaml:/app/moclojer.yml ghcr.io/moclojer/moclojer:latest`

### moclojer config

```yaml
- endpoint:
    method: GET
    path: /url/:url
    response:
      status: 200
      headers:
        Content-Type: text/markdown
      body: >
        The text describes a conversation between an orbiter in space and Houston, where the orbiter reports a problem with its O2 tank. The person in Houston responds dismissively and ends the call. The text also includes a humorous title text and a note about the preferred viewing conditions for xkcd.com.
- endpoint:
    method: POST
    path: /summarize
    response:
      status: 303
      headers:
        Content-Type: application/json
      body: ""
```

### Version and environment information

moclojer version: v0.3.0

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)
