### ISSUE TITLE
webhook: conditions to control execution aka `if`

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#235]
Not in all cases do we want to trigger a webhook, even if it's configured in the mock.
For example, I want to trigger the hook when the field/param `﻿username` has the value ﻿`moclojer`

```yaml
- endpoint:
    method: POST
    path: /send-webhook-if/:username
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {"reciver": true}
    webhook:
      if: {{path-params.username}} == "moclojer"
      sleep-time: 0
      url: https://...
      method: POST
      headers:
        Content-Type: application/json
      body: >
        {"username": "{{path-params.username}}"}
```

`if` by default is `true`, it's a condition, so the expected return is a boolean.

[reference github action](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution)
```yaml
if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
```
