### ISSUE TITLE
HTTP header parameters as variables

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#251]
Some APIs use header fields to send information, it's important to make these parameters available to be consumed in the specification, allowing the user to create logic with this data.

`{{header-params.XXX}}`

```yaml
Request URL: https://...
Request method: POST
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/...
X-GitHub-Delivery: ...
X-GitHub-Event: issues
X-GitHub-Hook-ID: ...
X-GitHub-Hook-Installation-Target-ID: ...
X-GitHub-Hook-Installation-Target-Type: repository
```
