### ISSUE TITLE
Improve error handler on the route level

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#253]
implement an "interceptor" to capture and format errors in the API output in a "user-friendly" way

### Discussed in https://github.com/moclojer/moclojer/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **matheusfrancisco** April 16, 2024</sup>
When I added a mock with an invalid body an exception happened, moclojer should be able to handle it and present some information like 
{status: 500,  body: "error"} 

```yml
# The following schema is an example of how you can
# use the power of Moclojer to create your applications.
#
# Documentation: https://docs.moclojer.com
# Source Code: https://github.com/moclojer/moclojer

# This mock register route: GET /hello/:username
- endpoint:
    # Note: the method could be omitted because GET is the default
    method: GET
    path: /helloo/:username
    response:
      # Note: the status could be omitted because 200 is the default
      status: 200
      headers:
        Content-Type: application/json
      # Note: the body will receive the value passed in the url using the
      # :username placeholder
      body: |
        {{}
          "hello": "{{path-params.username}}!"
        }

```

</div>
