### ISSUE TITLE
webhook headers aren't being parsed correctly

### ISSUE THREAD

**Issue by J0sueTM** [moclojer/moclojer#263]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When running a webhook, the headers are not being retrieved correctly.

### Reproduce the Bug

Run moclojer with a config with a webook that uses the headers from the requests

### moclojer config

```yaml
- endpoint:
    method: POST
    path: /github/:repo
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {"reciver": true}
    webhook:
      sleep-time: 0
      url: https://discord.com/api/webhooks/1230521862652428332/<retracted>/github
      method: POST
      headers:
        Content-Type: application/json
        X-GitHub-Delivery: {{headers.x-github-delivery}}
        X-GitHub-Event: {{headers.x-github-event}}
        X-GitHub-Hook-ID: {{headers.x-github-hook-id}}
        X-GitHub-Hook-Installation-Target-ID: {{headers.x-github-installation-target-id}}
        X-GitHub-Hook-Installation-Target-Type: {{headers.x-github-installation-target-type}}
      body: "{{json-params}}"
```

### Expected Behavior

For the request to proceed correctly

### Version and environment information

current HEAD sha: `b60da6774abfc0ad8e77cc70124eb45f85f91759`
OS: linux (arch)

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)
