### ISSUE TITLE
Implementation of Chaos Testing

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#303]
Implement a robust Chaos Testing system for Moclojer, allowing controlled simulation of adverse conditions in API endpoints.

1. Latency Simulation
- Add random delays to responses
- Configurable through:
  - Minimum time (min-ms)
  - Maximum time (max-ms)
  - Occurrence probability
  - Enable/disable flag

2. Failure Simulation
- Return 500 errors in a controlled manner
- Configurable through:
  - Failure probability
  - Enable/disable flag
- Custom error message indicating chaos testing

3. Data Corruption Simulation
- Modify responses to simulate data corruption
- Configurable through:
  - Corruption probability
  - Enable/disable flag
- Add `chaos_corruption: true` marker in affected responses

## Configuration

Implementation will be done via middleware and configurable through endpoint metadata in YAML:

```yaml
chaos:
  latency:
    enabled: true
    min-ms: 100
    max-ms: 1000
    probability: 0.2
  failures:
    enabled: true
    probability: 0.1
  corruption:
    enabled: true
    probability: 0.1
```
