### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#316]
It would be important to support websocket, not just http server.

Configuration proposal (`yaml`)

```yaml
- websocket:
    path: /ws/echo
    on-connect:
      response: '{"status": "connected", "message": "Bem-vindo ao WebSocket Echo!"}'
    on-message:
      - pattern: "ping"
        response: "pong"
      - pattern: '{"echo": "{{json-params.echo}}"}'
        response: '{"echoed": "{{json-params.echo}}"}'
```
