### ISSUE TITLE
Global configuration valid for all endpoints, starting with external content folder setup

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#328]
It is common to have some variables that we want to use globally instead of having to declare in each `endpoint`.
We need to think about a structure to support these configurations.

The first case to support is that it came up in this discussion from @michaldo, to configure the default folder for the **external body**

**How did I imagine the configuration?**

```yaml
external-body:
  folder: ./bodies

- endpoint:
    method: POST
    ...
```

### Discussed in https://github.com/orgs/moclojer/discussions/326

<div type='discussions-op-text'>

<sup>Originally posted by **@michaldo** June  5, 2025</sup>
I'm using moclojer with docker compose. I have folder with N bodies, let say `/host/bodies`
My `docker-compose.yaml` has section

```
volumes:
  - /host/bodies:/app/bodies
```

**My `moclojer.yml` has:**
```
- endpoint:
    method: POST
    path: /body1
    response:
      external-body:
        provider: json
        path: bodies/body1.json
```

I'm not satisfied I had to repeat "path: **bodies**/body1.json" N times

I would be happy to repeat `path: body1.json`

If there is a configuration option like `external-bodies-base-folder=./bodies` my moclojer.yml will be simpler</div>
