### ISSUE TITLE
Running inside docker in http server is not publicly exposed

### ISSUE THREAD

**Issue by avelino** [moclojer/moclojer#67]
by running moclojer in the docker image the http server is not outside docker, only inside docker

`docker-compose.yml`:
```yaml
version: '3'

services:
  moclojer:
    image: ghcr.io/moclojer/moclojer:dev
    platform: linux/amd64
    ports:
      - 8000:8000
    volumes:
      - ./moclojer.yml:/app/moclojer.yml
```

`moclojer.yml`:
```yaml
# This mock register route: GET /hello/:username
- endpoint:
    # Note: the method could be omitted because GET is the default
    method: GET
    path: /hello/:username
    response:
      # Note: the status could be omitted because 200 is the default
      status: 200
      headers:
        Content-Type: application/json
      # Note: the body will receive the value passed in the url using the
      # :username placeholder
      body: >
        {
          "hello": "{{path-params.username}}!"
        }
```

report by @wesleywillians
